
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return( 


    <header className="bg-gray-500 py-4">

      <div className="container mx-auto px-4">

      <nav className="flex items-center justify-start space-x-4">


        <div className="flex item-center text-xl font-bold text-white m-5...">
          <Link href ="/">Home</Link>
        </div>  
          
       <div className="flex item-center text-xl font-bold text-white">
          <Link href ="/aboutus">About Us</Link>
          </div>
   
        <div className="flex item-center text-xl font-bold text-white">
          <Link href ="/contactme">Contact Me</Link>
        </div>
        <div className="flex item-center text-xl font-bold text-white">
          <Link href ="/project">Projects</Link>
        </div>
        
      </nav>
</div>
    </header>
  );
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
